
trigger:
- master

resources:
- repo: self

variables:
   imageName: 'game'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:  
  - job: Build
    displayName: Build job
    pool:
      vmImage: 'ubuntu-latest' 
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: oukchiren/game1
        dockerfile: Dockerfile
        containerRegistry: oukchiren

- stage: Deploy
  jobs:
  - job: Deploy
    steps:
  
    - task: AzureCLI@2
      inputs:
       azureSubscription: 'Azure for Students(dd159ed8-ec35-4c43-a350-81fd38bb245b)'
       scriptType: 'bash'
       scriptLocation: 'inlineScript'
       inlineScript: |
        az aks get-credentials --resource-group aks_tf_rg --name my-aks-cluster

    - script: cat 01_kubernetes_aks/app-deploy.yaml
    
    - task: Kubernetes@1
      inputs:
       connectionType: 'Azure Resource Manager'
       azureSubscriptionEndpoint: 'Azure for Students(dd159ed8-ec35-4c43-a350-81fd38bb245b)'
       azureResourceGroup: 'aks_tf_rg'
       kubernetesCluster: 'my-aks-cluster'
       namespace: 'default'
       command: 'apply'
       useConfigurationFile: true
       configuration: 'deployment.yaml'
       secretType: 'dockerRegistry'
       azureSubscriptionEndpointForSecrets: 'Azure for Students(dd159ed8-ec35-4c43-a350-81fd38bb245b)'
       forceUpdate: false